
spring.application.name=GatewayMs

# SERVER
server.port=${PORT:8080}

# =========================
# USER SERVICE ROUTE
# =========================

spring.cloud.gateway.server.webflux.routes[0].id=UserMs
spring.cloud.gateway.server.webflux.routes[0].uri=${USER_MS_URL}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=TokenFilter

# =========================
# DOCTOR SERVICE ROUTE
# =========================

spring.cloud.gateway.server.webflux.routes[1].id=DoctorMs
spring.cloud.gateway.server.webflux.routes[1].uri=${DOCTOR_MS_URL}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/doctor/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=TokenFilter

# =========================
# PATIENT SERVICE ROUTE
# =========================

spring.cloud.gateway.server.webflux.routes[2].id=PatientMs
spring.cloud.gateway.server.webflux.routes[2].uri=${PATIENT_MS_URL}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/patient/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=TokenFilter

# =========================
# APPOINTMENT SERVICE ROUTE
# =========================

spring.cloud.gateway.server.webflux.routes[3].id=AppointmentMs
spring.cloud.gateway.server.webflux.routes[3].uri=${APPOINTMENT_MS_URL}
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/appointment/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=TokenFilter

# =========================
# CORS
# =========================

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

# Replace with your deployed frontend URL
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins[0]=${FRONTEND_URL:http://localhost:5173}

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders[0]=*
spring.cloud.gateway.server.webflux.globalcors.globalcors.cors-configurations.[/**].allowCredentials=true

# =========================
# LOGGING
# =========================

logging.level.org.springframework.cloud.gateway=INFO